// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignIn.proto

package com.vulpes.word.Model;

public final class SignInMessage {
  private SignInMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SignInRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SignInRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code SignInRequest}
   */
  public  static final class SignInRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SignInRequest)
      SignInRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignInRequest.newBuilder() to construct.
    private SignInRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignInRequest() {
      username_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignInRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vulpes.word.Model.SignInMessage.internal_static_SignInRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vulpes.word.Model.SignInMessage.internal_static_SignInRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vulpes.word.Model.SignInMessage.SignInRequest.class, com.vulpes.word.Model.SignInMessage.SignInRequest.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vulpes.word.Model.SignInMessage.SignInRequest)) {
        return super.equals(obj);
      }
      com.vulpes.word.Model.SignInMessage.SignInRequest other = (com.vulpes.word.Model.SignInMessage.SignInRequest) obj;

      boolean result = true;
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vulpes.word.Model.SignInMessage.SignInRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SignInRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SignInRequest)
        com.vulpes.word.Model.SignInMessage.SignInRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vulpes.word.Model.SignInMessage.internal_static_SignInRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vulpes.word.Model.SignInMessage.internal_static_SignInRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vulpes.word.Model.SignInMessage.SignInRequest.class, com.vulpes.word.Model.SignInMessage.SignInRequest.Builder.class);
      }

      // Construct using com.vulpes.word.Model.SignInMessage.SignInRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        username_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vulpes.word.Model.SignInMessage.internal_static_SignInRequest_descriptor;
      }

      public com.vulpes.word.Model.SignInMessage.SignInRequest getDefaultInstanceForType() {
        return com.vulpes.word.Model.SignInMessage.SignInRequest.getDefaultInstance();
      }

      public com.vulpes.word.Model.SignInMessage.SignInRequest build() {
        com.vulpes.word.Model.SignInMessage.SignInRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vulpes.word.Model.SignInMessage.SignInRequest buildPartial() {
        com.vulpes.word.Model.SignInMessage.SignInRequest result = new com.vulpes.word.Model.SignInMessage.SignInRequest(this);
        result.username_ = username_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vulpes.word.Model.SignInMessage.SignInRequest) {
          return mergeFrom((com.vulpes.word.Model.SignInMessage.SignInRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vulpes.word.Model.SignInMessage.SignInRequest other) {
        if (other == com.vulpes.word.Model.SignInMessage.SignInRequest.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vulpes.word.Model.SignInMessage.SignInRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vulpes.word.Model.SignInMessage.SignInRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SignInRequest)
    }

    // @@protoc_insertion_point(class_scope:SignInRequest)
    private static final com.vulpes.word.Model.SignInMessage.SignInRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vulpes.word.Model.SignInMessage.SignInRequest();
    }

    public static com.vulpes.word.Model.SignInMessage.SignInRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignInRequest>
        PARSER = new com.google.protobuf.AbstractParser<SignInRequest>() {
      public SignInRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignInRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignInRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignInRequest> getParserForType() {
      return PARSER;
    }

    public com.vulpes.word.Model.SignInMessage.SignInRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignInResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SignInResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    com.vulpes.word.Model.ResponseMessage.ResponseHeader getHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    com.vulpes.word.Model.ResponseMessage.ResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.AccountInfo account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <code>.AccountInfo account = 2;</code>
     */
    com.vulpes.word.Model.AccountMessage.AccountInfo getAccount();
    /**
     * <code>.AccountInfo account = 2;</code>
     */
    com.vulpes.word.Model.AccountMessage.AccountInfoOrBuilder getAccountOrBuilder();
  }
  /**
   * Protobuf type {@code SignInResponse}
   */
  public  static final class SignInResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SignInResponse)
      SignInResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignInResponse.newBuilder() to construct.
    private SignInResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignInResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignInResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.vulpes.word.Model.ResponseMessage.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.vulpes.word.Model.ResponseMessage.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.vulpes.word.Model.AccountMessage.AccountInfo.Builder subBuilder = null;
              if (account_ != null) {
                subBuilder = account_.toBuilder();
              }
              account_ = input.readMessage(com.vulpes.word.Model.AccountMessage.AccountInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(account_);
                account_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vulpes.word.Model.SignInMessage.internal_static_SignInResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vulpes.word.Model.SignInMessage.internal_static_SignInResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vulpes.word.Model.SignInMessage.SignInResponse.class, com.vulpes.word.Model.SignInMessage.SignInResponse.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.vulpes.word.Model.ResponseMessage.ResponseHeader header_;
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public com.vulpes.word.Model.ResponseMessage.ResponseHeader getHeader() {
      return header_ == null ? com.vulpes.word.Model.ResponseMessage.ResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public com.vulpes.word.Model.ResponseMessage.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private com.vulpes.word.Model.AccountMessage.AccountInfo account_;
    /**
     * <code>.AccountInfo account = 2;</code>
     */
    public boolean hasAccount() {
      return account_ != null;
    }
    /**
     * <code>.AccountInfo account = 2;</code>
     */
    public com.vulpes.word.Model.AccountMessage.AccountInfo getAccount() {
      return account_ == null ? com.vulpes.word.Model.AccountMessage.AccountInfo.getDefaultInstance() : account_;
    }
    /**
     * <code>.AccountInfo account = 2;</code>
     */
    public com.vulpes.word.Model.AccountMessage.AccountInfoOrBuilder getAccountOrBuilder() {
      return getAccount();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (account_ != null) {
        output.writeMessage(2, getAccount());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (account_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAccount());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vulpes.word.Model.SignInMessage.SignInResponse)) {
        return super.equals(obj);
      }
      com.vulpes.word.Model.SignInMessage.SignInResponse other = (com.vulpes.word.Model.SignInMessage.SignInResponse) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasAccount() == other.hasAccount());
      if (hasAccount()) {
        result = result && getAccount()
            .equals(other.getAccount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasAccount()) {
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccount().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vulpes.word.Model.SignInMessage.SignInResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vulpes.word.Model.SignInMessage.SignInResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SignInResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SignInResponse)
        com.vulpes.word.Model.SignInMessage.SignInResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vulpes.word.Model.SignInMessage.internal_static_SignInResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vulpes.word.Model.SignInMessage.internal_static_SignInResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vulpes.word.Model.SignInMessage.SignInResponse.class, com.vulpes.word.Model.SignInMessage.SignInResponse.Builder.class);
      }

      // Construct using com.vulpes.word.Model.SignInMessage.SignInResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (accountBuilder_ == null) {
          account_ = null;
        } else {
          account_ = null;
          accountBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vulpes.word.Model.SignInMessage.internal_static_SignInResponse_descriptor;
      }

      public com.vulpes.word.Model.SignInMessage.SignInResponse getDefaultInstanceForType() {
        return com.vulpes.word.Model.SignInMessage.SignInResponse.getDefaultInstance();
      }

      public com.vulpes.word.Model.SignInMessage.SignInResponse build() {
        com.vulpes.word.Model.SignInMessage.SignInResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vulpes.word.Model.SignInMessage.SignInResponse buildPartial() {
        com.vulpes.word.Model.SignInMessage.SignInResponse result = new com.vulpes.word.Model.SignInMessage.SignInResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (accountBuilder_ == null) {
          result.account_ = account_;
        } else {
          result.account_ = accountBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vulpes.word.Model.SignInMessage.SignInResponse) {
          return mergeFrom((com.vulpes.word.Model.SignInMessage.SignInResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vulpes.word.Model.SignInMessage.SignInResponse other) {
        if (other == com.vulpes.word.Model.SignInMessage.SignInResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasAccount()) {
          mergeAccount(other.getAccount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vulpes.word.Model.SignInMessage.SignInResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vulpes.word.Model.SignInMessage.SignInResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.vulpes.word.Model.ResponseMessage.ResponseHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vulpes.word.Model.ResponseMessage.ResponseHeader, com.vulpes.word.Model.ResponseMessage.ResponseHeader.Builder, com.vulpes.word.Model.ResponseMessage.ResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public com.vulpes.word.Model.ResponseMessage.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.vulpes.word.Model.ResponseMessage.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(com.vulpes.word.Model.ResponseMessage.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          com.vulpes.word.Model.ResponseMessage.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(com.vulpes.word.Model.ResponseMessage.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.vulpes.word.Model.ResponseMessage.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public com.vulpes.word.Model.ResponseMessage.ResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public com.vulpes.word.Model.ResponseMessage.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.vulpes.word.Model.ResponseMessage.ResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vulpes.word.Model.ResponseMessage.ResponseHeader, com.vulpes.word.Model.ResponseMessage.ResponseHeader.Builder, com.vulpes.word.Model.ResponseMessage.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.vulpes.word.Model.ResponseMessage.ResponseHeader, com.vulpes.word.Model.ResponseMessage.ResponseHeader.Builder, com.vulpes.word.Model.ResponseMessage.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.vulpes.word.Model.AccountMessage.AccountInfo account_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vulpes.word.Model.AccountMessage.AccountInfo, com.vulpes.word.Model.AccountMessage.AccountInfo.Builder, com.vulpes.word.Model.AccountMessage.AccountInfoOrBuilder> accountBuilder_;
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public boolean hasAccount() {
        return accountBuilder_ != null || account_ != null;
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public com.vulpes.word.Model.AccountMessage.AccountInfo getAccount() {
        if (accountBuilder_ == null) {
          return account_ == null ? com.vulpes.word.Model.AccountMessage.AccountInfo.getDefaultInstance() : account_;
        } else {
          return accountBuilder_.getMessage();
        }
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public Builder setAccount(com.vulpes.word.Model.AccountMessage.AccountInfo value) {
        if (accountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          account_ = value;
          onChanged();
        } else {
          accountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public Builder setAccount(
          com.vulpes.word.Model.AccountMessage.AccountInfo.Builder builderForValue) {
        if (accountBuilder_ == null) {
          account_ = builderForValue.build();
          onChanged();
        } else {
          accountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public Builder mergeAccount(com.vulpes.word.Model.AccountMessage.AccountInfo value) {
        if (accountBuilder_ == null) {
          if (account_ != null) {
            account_ =
              com.vulpes.word.Model.AccountMessage.AccountInfo.newBuilder(account_).mergeFrom(value).buildPartial();
          } else {
            account_ = value;
          }
          onChanged();
        } else {
          accountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public Builder clearAccount() {
        if (accountBuilder_ == null) {
          account_ = null;
          onChanged();
        } else {
          account_ = null;
          accountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public com.vulpes.word.Model.AccountMessage.AccountInfo.Builder getAccountBuilder() {
        
        onChanged();
        return getAccountFieldBuilder().getBuilder();
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      public com.vulpes.word.Model.AccountMessage.AccountInfoOrBuilder getAccountOrBuilder() {
        if (accountBuilder_ != null) {
          return accountBuilder_.getMessageOrBuilder();
        } else {
          return account_ == null ?
              com.vulpes.word.Model.AccountMessage.AccountInfo.getDefaultInstance() : account_;
        }
      }
      /**
       * <code>.AccountInfo account = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vulpes.word.Model.AccountMessage.AccountInfo, com.vulpes.word.Model.AccountMessage.AccountInfo.Builder, com.vulpes.word.Model.AccountMessage.AccountInfoOrBuilder> 
          getAccountFieldBuilder() {
        if (accountBuilder_ == null) {
          accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.vulpes.word.Model.AccountMessage.AccountInfo, com.vulpes.word.Model.AccountMessage.AccountInfo.Builder, com.vulpes.word.Model.AccountMessage.AccountInfoOrBuilder>(
                  getAccount(),
                  getParentForChildren(),
                  isClean());
          account_ = null;
        }
        return accountBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SignInResponse)
    }

    // @@protoc_insertion_point(class_scope:SignInResponse)
    private static final com.vulpes.word.Model.SignInMessage.SignInResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vulpes.word.Model.SignInMessage.SignInResponse();
    }

    public static com.vulpes.word.Model.SignInMessage.SignInResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignInResponse>
        PARSER = new com.google.protobuf.AbstractParser<SignInResponse>() {
      public SignInResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignInResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignInResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignInResponse> getParserForType() {
      return PARSER;
    }

    public com.vulpes.word.Model.SignInMessage.SignInResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SignInRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SignInRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SignInResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SignInResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014SignIn.proto\032\024ResponseHeader.proto\032\rAc" +
      "count.proto\"3\n\rSignInRequest\022\020\n\010username" +
      "\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"P\n\016SignInRespon" +
      "se\022\037\n\006header\030\001 \001(\0132\017.ResponseHeader\022\035\n\007a" +
      "ccount\030\002 \001(\0132\014.AccountInfoB&\n\025com.vulpes" +
      ".word.ModelB\rSignInMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vulpes.word.Model.ResponseMessage.getDescriptor(),
          com.vulpes.word.Model.AccountMessage.getDescriptor(),
        }, assigner);
    internal_static_SignInRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SignInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SignInRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_SignInResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SignInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SignInResponse_descriptor,
        new java.lang.String[] { "Header", "Account", });
    com.vulpes.word.Model.ResponseMessage.getDescriptor();
    com.vulpes.word.Model.AccountMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
